version: '3.8'

services:
  monitoramento-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
      - SPRING_DATASOURCE_USERNAME=rm558743
      - SPRING_DATASOURCE_PASSWORD=140601